#!/usr/bin/env bash
# Generate AGENTS.md and AGENTS.override.md from docs/agents/ sources.
# Walks docs/agents/ recursively: for the root and every subdirectory that
# contains a core.md or codex.md, emits the corresponding AGENTS.md and/or
# AGENTS.override.md at the matching path in the destination tree.
# Deterministic: same inputs produce byte-identical output.
#
# CLAUDE.md is intentionally NOT generated — it is hand-authored as an
# @import dispatcher that references docs/agents/[<path>/]{core,claude}.md
# at read time. This preserves live-reload for Claude Code while still
# drawing from the same shared source files.
#
# Usage:
#   /agents-docs-build                                       # via the workflow-claude plugin
#   bash scripts/build-agents-md.sh                          # direct
#   DST_DIR=/tmp/out bash scripts/build-agents-md.sh         # used by check-agents-md.sh
#
# Consumers normally invoke /agents-docs-build rather than this script.

set -euo pipefail

ROOT="$(git rev-parse --show-toplevel)"
SRC_DIR="${ROOT}/docs/agents"
DST_DIR="${DST_DIR:-${ROOT}}"

if [ ! -d "$SRC_DIR" ]; then
  echo "error: ${SRC_DIR} not found" >&2
  echo "Expected layout: docs/agents/{core.md,codex.md,claude.md} at the repo root" >&2
  exit 1
fi

# Source -> destination basename pairs. Applied at the root and at every
# component subdirectory under docs/agents/.
PAIRS=(
  "core.md|AGENTS.md"
  "codex.md|AGENTS.override.md"
)

# Plan all (src_path, dest_path, rel) triples before writing anything.
declare -a PLAN_SRC=() PLAN_DST=() PLAN_REL=()

while IFS= read -r dir; do
  rel="${dir#"$SRC_DIR"}"
  rel="${rel#/}"  # "" for the root, "<comp>" or "<comp>/<sub>" otherwise

  for pair in "${PAIRS[@]}"; do
    src_basename="${pair%|*}"
    dst_basename="${pair#*|}"

    src_path="${dir}/${src_basename}"
    [ -f "$src_path" ] || continue

    if [ -z "$rel" ]; then
      dst_path="${DST_DIR}/${dst_basename}"
    else
      dst_path="${DST_DIR}/${rel}/${dst_basename}"
    fi

    PLAN_SRC+=("$src_path")
    PLAN_DST+=("$dst_path")
    PLAN_REL+=("$rel")
  done
done < <(find "$SRC_DIR" -type d | sort)

if [ "${#PLAN_SRC[@]}" -eq 0 ]; then
  echo "error: no core.md or codex.md found anywhere under ${SRC_DIR}" >&2
  exit 1
fi

# Pre-flight: confirm every planned source still exists.
for i in "${!PLAN_SRC[@]}"; do
  if [ ! -f "${PLAN_SRC[$i]}" ]; then
    echo "error: ${PLAN_SRC[$i]} disappeared before write" >&2
    exit 1
  fi
done

# Build each target.
for i in "${!PLAN_SRC[@]}"; do
  src_path="${PLAN_SRC[$i]}"
  dst_path="${PLAN_DST[$i]}"
  rel="${PLAN_REL[$i]}"

  if [ -z "$rel" ]; then
    header_source="docs/agents/$(basename "$src_path")"
  else
    header_source="docs/agents/${rel}/$(basename "$src_path")"
  fi

  mkdir -p "$(dirname "$dst_path")"

  {
    echo "<!-- Generated from ${header_source}."
    echo "     Regenerate with /agents-docs-build. Do not edit this file directly. -->"
    echo
    cat "$src_path"
  } > "$dst_path"

  echo "wrote ${dst_path} ($(wc -l < "$dst_path" | tr -d ' ') lines)"
done
